name: Gerar APK do CRGBDA.AI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar os arquivos do seu projeto
        uses: actions/checkout@v4

      - name: Instalar tudo o que precisa
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv openjdk-17-jdk zip unzip
          pip3 install --upgrade pip --break-system-packages
          pip3 install buildozer cython python-dotenv --break-system-packages

      - name: Gerar o APK
        run: |
          buildozer android debug

      - name: Salvar o APK pronto
        uses: actions/upload-artifact@v4
        with:
          name: CRGBDA_APK_PRONTO
          path: bin/*.apk
